image: gitpod/workspace-node-18

tasks:
  - init: yarn add truffle && yarn add ganache && yarn install
    command: >
      cd lab1/blockchain && 
      npx truffle develop &&
      gp sync-done truffle
  - name: ganache
    init: gp sync-await truffle
    command: >
      cd lab1/blockchain && 
      npx ganache --seed myCustomSeed &&
      gp sync-done ganache
    openMode: split-right	
  - name: contrato
    init: gp sync-await ganache
    command: >
      cd lab1/blockchain && 
      npx truffle migrate --network ganache
      openMode: split-right
