image: gitpod/workspace-node-18

tasks:
  - init: yarn add truffle && yarn add ganache && yarn install
    command: cd lab1/blockchain && npx truffle develop
  - name: ganache
    command: cd lab1/blockchain && npx ganache --seed myCustomSeed
  - name: contrato
    command: cd lab1/blockchain && npx truffle migrate --network ganache
