image: gitpod/workspace-node-18

tasks:
  - init: yarn add truffle && yarn add ganache && yarn install
    #command: yarn run start 
    command: npx truffle develop
    #command: npx ganache-cli --seed myCustomSeed